Test

diff --git a/.github/workflows/test-kitchen.yml b/.github/workflows/test-kitchen.yml
--- a/.github/workflows/test-kitchen.yml
+++ b/.github/workflows/test-kitchen.yml
@@ -49,4 +49,5 @@ jobs:
         run: |
           kitchen destroy
           knife node list -c .chef/config.rb | grep "default-*" | xargs knife node delete -y -c .chef/config.rb || echo "node deletion failed somehow"
-          knife client list -c .chef/config.rb | grep "default-*" | xargs knife client delete -y -c .chef/config.rb || echo "client delete failed somehow"        
+          knife client list -c .chef/config.rb | grep "default-*" | xargs knife client delete -y -c .chef/config.rb || echo "client delete failed somehow"
+          echo $slack_webhook_url
